static const char clangdTemplate[] = 
"CompileFlags:\n"
"\tAdd: [-xc, -std=gnu23]"
"";

static const char mainTemplate[] = 
"#include <stdio.h>\n"
"\n"
"int main() {\n"
"\tprintf(\"Hello World\\n\");\n"
"\treturn 0;\n"
"}\n"
"";

static const char makefileTargetsTemplate[] = 
"# =====================================\n"
"# MySetupProject targets.mk template v0.4\n"
"# =====================================\n"
"# This file defines the targets to be compiled.\n"
"# Read Makefile for more information\n"
"# =====================================\n"
"\n"
"TARGET := $(notdir $(CURDIR))\n"
"\n"
"TARGETS := $(TARGET)\n"
"\n"
"$(TARGET)_DIR  := src\n"
"$(TARGET)_TYPE := executable\n"
"";

static const char makefileConfigTemplate[] = 
"# =====================================\n"
"# MySetupProject config.mk template v0.4\n"
"# =====================================\n"
"# This file simplifies the use of custom build options.\n"
"# Read Makefile for more information\n"
"# =====================================\n"
"\n"
"# -------- Feature toggles --------\n"
"# Set to 1 to enable\n"
"USER_ENABLE_SANITIZERS := 0\n"
"USER_ENABLE_WARNINGS_AS_ERRORS := 0\n"
"USER_ENABLE_LTO := 0\n"
"\n"
"# -------- Include directories --------\n"
"# Example:\n"
"# USER_INCLUDES := -Ithirdparty/imgui\n"
"USER_INCLUDES :=\n"
"\n"
"# -------- Library search paths --------\n"
"# Example:\n"
"# USER_LIB_PATHS := -Lthirdparty/lib\n"
"USER_LIB_PATHS :=\n"
"\n"
"# -------- Libraries to link --------\n"
"# Example:\n"
"# USER_LIBS := -lm -lSDL2\n"
"USER_LIBS :=\n"
"\n"
"# -------- Extra compiler flags --------\n"
"USER_CFLAGS :=\n"
"\n"
"# -------- Extra linker flags --------\n"
"USER_LDFLAGS :=\n"
"\n"
"# -------- Custom build hooks --------\n"
"# These are appended to default rules\n"
"USER_PRE_BUILD :=\n"
"USER_POST_BUILD :=\n"
"";

static const char makefileTemplate[] =
"# =====================================\n"
"# MySetupProject Makefile template v0.4\n"
"#\n"
"# Update logs v0.4:\n"
"#   - Update logs were introduced\n"
"#   - Toolchain variables now are setted with ?=\n"
"#   - RELEASE_CFLAGS uses -O2 instead of -O3\n"
"#\t- Standard build mode changed to release\n"
"#\t- Now is possible to compile multiple targets:\n"
"#\t\tTargets are generated dynamically, to implement a new target\n"
"#\t\topen targets.mk and add the target name into zTARGETS\n"
"#\t\tthen you must generate [target]_DIR wich contains the root directory\n"
"#\t\tof the source files (admits subdirs) and [target]_TYPE := (executable / static)\n"
"#\t- TODO: Add shared libraries compilation\n"
"# =====================================\n"
"# EDIT WITH PRECAUTION.\n"
"# =====================================\n"
"\n"
"# -------- Crossplatform --------\n"
"\n"
"ifeq ($(OS),Windows_NT)\n"
"    MKDIR = mkdir \"$(1)\" 2>nul || exit 0\n"
"    RMDIR = if exist \"$(1)\" rmdir /S /Q \"$(1)\"\n"
"else\n"
"    MKDIR = mkdir -p \"$(1)\"\n"
"    RMDIR = rm -rf \"$(1)\"\n"
"endif\n"
"\n"
"# Recursive wildcard\n"
"rwildcard = $(filter $(subst *,%,$2),$(wildcard $1/$2)) \\\n"
"            $(foreach d,$(wildcard $1/*),$(call rwildcard,$d,$2))\n"
"\n"
"# -------- Project layout --------\n"
"SRC_FOLDER := src\n"
"OBJ_FOLDER := obj\n"
"BIN_FOLDER := bin\n"
"LIB_FOLDER := lib\n"
"\n"
"DEBUG_FOLDER := debug\n"
"RELEASE_FOLDER := release\n"
"\n"
"# -------- Build tools --------\n"
"\n"
"MODE ?= release\n"
"CVERSION ?= 23\n"
"\n"
"CC := gcc\n"
"AR := ar\n"
"AS := nasm\n"
"\n"
"CFLAGS ?= -Iinclude -Wall -Wextra -MMD -MP\n"
"ifneq ($(CVERSION),Default)\n"
"\tCFLAGS += -std=gnu$(CVERSION)\n"
"endif\n"
"\n"
"LDFLAGS ?= \n"
"\n"
"# -------- Release or Debug specifics --------\n"
"\n"
"DEBUG_CFLAGS := -g -O0 -DDEBUG\t\n"
"RELEASE_CFLAGS := -O2 -DNDEBUG\n"
"\n"
"ifeq ($(MODE),release)\n"
"\tCFLAGS += $(RELEASE_CFLAGS)\n"
"\tLIB_PATH \t:= $(LIB_FOLDER)/$(RELEASE_FOLDER)\n"
"\tBIN_PATH \t:= $(BIN_FOLDER)/$(RELEASE_FOLDER)\n"
"\tOBJ_PATH \t:= $(OBJ_FOLDER)/$(RELEASE_FOLDER)\n"
"else\n"
"\tCFLAGS += $(DEBUG_CFLAGS)\n"
"\tLIB_PATH \t:= $(LIB_FOLDER)/$(DEBUG_FOLDER)\n"
"\tBIN_PATH \t:= $(BIN_FOLDER)/$(DEBUG_FOLDER)\n"
"\tOBJ_PATH \t:= $(OBJ_FOLDER)/$(DEBUG_FOLDER)\n"
"endif\n"
"\n"
"\n"
"# -------- User Configuration --------\n"
"\n"
"-include config.mk\n"
"\n"
"USER_INCLUDES ?=\n"
"USER_LIB_PATHS ?=\n"
"USER_LIBS ?=\n"
"USER_CFLAGS ?=\n"
"USER_LDFLAGS ?=\n"
"USER_PRE_BUILD ?=\n"
"USER_POST_BUILD ?=\n"
"\n"
"USER_ENABLE_SANITIZERS ?= 0\n"
"USER_ENABLE_WARNINGS_AS_ERRORS ?= 0\n"
"USER_ENABLE_LTO ?= 0\n"
"\n"
"ifeq ($(USER_ENABLE_SANITIZERS),1)\n"
"\tCFLAGS += -fsanitize=address,undefined\n"
"\tLDFLAGS += -fsanitize=address,undefined\n"
"endif\n"
"\n"
"ifeq ($(USER_ENABLE_WARNINGS_AS_ERRORS),1)\n"
"\tCFLAGS += -Werror\n"
"endif\n"
"\n"
"ifeq ($(USER_ENABLE_LTO),1)\n"
"\tCFLAGS += -flto\n"
"\tLDFLAGS += -flto\n"
"endif\n"
"\n"
"CFLAGS  += $(USER_INCLUDES) $(USER_CFLAGS)\n"
"LDFLAGS += $(USER_LIB_PATHS) $(USER_LDFLAGS)\n"
"\n"
"# -------- Phony targets --------\n"
"\n"
"include targets.mk\n"
"\n"
".PHONY: all clean\n"
"\n"
"all: $(TARGETS)\n"
"\n"
"clean:\n"
"\t@$(call RMDIR,$(OBJ_FOLDER))\n"
"\t@$(call RMDIR,$(BIN_FOLDER))\n"
"\t@$(call RMDIR,$(LIB_FOLDER))\n"
"\n"
"# -------- Target generator --------\n"
"\n"
"define DEFINE_TARGET\n"
"\n"
"$(1)_DIR ?= src\n"
"$(1)_TYPE ?= executable\n"
"\n"
"$(1)_SRC_FILES := $$(call rwildcard,$$($(1)_DIR),*.c)\n"
"$(1)_REL_SRC := $$(patsubst $$($(1)_DIR)/%,%,$$($(1)_SRC_FILES))\n"
"$(1)_OBJ_FILES := $$(patsubst %.c,$$(OBJ_PATH)/$(1)/%.o,$$($(1)_REL_SRC))\n"
"$(1)_DEPS_FILES := $$($(1)_OBJ_FILES:.o=.d)\n"
"\n"
"ifeq ($$($(1)_TYPE),executable)\n"
"\n"
"$(1): $$(BIN_PATH)/$(1)\n"
"\n"
"$$(BIN_PATH)/$(1): $$($(1)_OBJ_FILES)\n"
"\t@$(call MKDIR,$$(dir $$@))\n"
"\t$$(USER_PRE_BUILD)\n"
"\t$$(CC) $$(CFLAGS) $$^ -o $$@ $$(LDFLAGS) $$(USER_LIBS)\n"
"\t$$(USER_POST_BUILD)\n"
"\n"
"endif\n"
"\n"
"ifeq ($$($(1)_TYPE),static)\n"
"\n"
"$(1): $$(LIB_PATH)/lib$(1).a\n"
"\n"
"$$(LIB_PATH)/lib$(1).a: $$($(1)_OBJ_FILES)\n"
"\t@$(call MKDIR,$$(dir $$@))\n"
"\t$$(USER_PRE_BUILD)\n"
"\t$$(AR) rcs $$@ $$^\n"
"\t$$(USER_POST_BUILD)\n"
"\n"
"endif\n"
"\n"
"$$(OBJ_PATH)/$(1)/%.o: $$($(1)_DIR)/%.c\n"
"\t@$$(call MKDIR,$$(dir $$@))\n"
"\t$$(CC) $$(CFLAGS) -c $$< -o $$@\n"
"\n"
"-include $$($(1)_DEPS_FILES)\n"
"\n"
"endef\n"
"\n"
"$(foreach target,$(TARGETS),$(eval $(call DEFINE_TARGET,$(target))))\n"
"";

static const char settingsTemplate[] = 
"{\n"
"\t\"C_Cpp.intelliSenseEngine\": \"disabled\",\n"
"\t\"clangd.arguments\": [\n"
"\t\t\"--query-driver=**\",\n"
"\t\t\"--header-insertion=never\",\n"
"\t\t\"--background-index\",\n"
"\t\t\"--clang-tidy\",\n"
"\t\t\"--completion-style=detailed\"\n"
"\t]\n"
"}\n"
"";

static const char MITLicense[] = 
"Permission is hereby granted, free of charge, to any person obtaining a copy\n"
"of this software and associated documentation files (the \"Software\"), to deal\n"
"in the Software without restriction, including without limitation the rights\n"
"to use, copy, modify, merge, publish, distribute, sublicense, and/or sell\n"
"copies of the Software, and to permit persons to whom the Software is\n"
"furnished to do so, subject to the following conditions:\n"
"\n"
"The above copyright notice and this permission notice shall be included in all\n"
"copies or substantial portions of the Software.\n"
"\n"
"THE SOFTWARE IS PROVIDED \"AS IS\", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR\n"
"IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,\n"
"FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE\n"
"AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER\n"
"LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,\n"
"OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE\n"
"SOFTWARE.\n"
"";

static const char gitignoreTemplate[] =
"# Prerequisites\n"
"*.d\n"
"\n"
"# Object files\n"
"*.o\n"
"*.ko\n"
"*.obj\n"
"*.elf\n"
"\n"
"# Linker output\n"
"*.ilk\n"
"*.map\n"
"*.exp\n"
"\n"
"# Precompiled Headers\n"
"*.gch\n"
"*.pch\n"
"\n"
"# Libraries\n"
"*.lib\n"
"*.a\n"
"*.la\n"
"*.lo\n"
"\n"
"# Shared objects (inc. Windows DLLs)\n"
"*.dll\n"
"*.so\n"
"*.so.*\n"
"*.dylib\n"
"\n"
"# Executables\n"
"*.exe\n"
"*.out\n"
"*.app\n"
"*.i*86\n"
"*.x86_64\n"
"*.hex\n"
"\n"
"# Debug files\n"
"*.dSYM/\n"
"*.su\n"
"*.idb\n"
"*.pdb\n"
"\n"
"# Kernel Module Compile Results\n"
"*.mod*\n"
"*.cmd\n"
".tmp_versions/\n"
"modules.order\n"
"Module.symvers\n"
"Mkfile.old\n"
"dkms.conf\n"
"\n"
"# debug information files\n"
"*.dwo\n"
"\n"
"# Project\n"
".clangd\n"
".vscode/\n"
"bin/\n"
"build/\n"
"\n";